name: Publish to PyPI

on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.baipp.outputs.package_version }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: hynek/build-and-inspect-python-package@b5076c307dc91924a82ad150cdd1533b444d3310 # v2.12.0
      id: baipp

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: publish
      url: https://pypi.org/project/meltano-rocksdb-state-backend/${{ needs.build.outputs.package_version }}

    steps:
    - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
