name: Publish to PyPI

on:
  push:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: publish
      url: https://pypi.org/p/meltano-rocksdb-state-backend

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@v1.10.2
